"""Rollup report generation — weekly and monthly summaries."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any

from jinja2 import Environment, FileSystemLoader, BaseLoader

from mssp_hunt_agent.analytics.kpi_engine import KPIEngine
from mssp_hunt_agent.analytics.models import MonthlyRollup, WeeklyRollup
from mssp_hunt_agent.persistence.database import HuntDatabase

logger = logging.getLogger(__name__)

# ── Inline templates (fallback when file templates not found) ────────

_WEEKLY_TEMPLATE = """\
# Weekly Hunt Rollup — {{ rollup.period }}

**Period:** {{ rollup.start_date }} to {{ rollup.end_date }}

## Summary

| Metric | Value |
|--------|-------|
| Active clients | {{ rollup.total_clients_active }} |
| Total hunts | {{ rollup.total_hunts }} |
| Total findings | {{ rollup.total_findings }} |
| High-confidence findings | {{ rollup.high_confidence_findings }} |

## Client Breakdown

| Client | Hunts | Findings | High-Conf | Hit Rate | Queries | Events |
|--------|-------|----------|-----------|----------|---------|--------|
{% for kpi in rollup.client_kpis -%}
| {{ kpi.client_name }} | {{ kpi.total_hunts }} | {{ kpi.total_findings }} | {{ kpi.high_confidence_findings }} | {{ "%.1f"|format(kpi.hit_rate * 100) }}% | {{ kpi.total_queries }} | {{ kpi.total_events }} |
{% endfor %}

{% if rollup.top_findings -%}
## Top Findings

| Title | Confidence | Count |
|-------|-----------|-------|
{% for f in rollup.top_findings -%}
| {{ f.title }} | {{ f.confidence }} | {{ f.cnt }} |
{% endfor %}
{% endif %}

---
*Generated by MSSP Hunt Agent Analytics*
"""

_MONTHLY_TEMPLATE = """\
# Monthly Hunt Rollup — {{ rollup.period }}

## Summary

| Metric | Value |
|--------|-------|
| Active clients | {{ rollup.total_clients_active }} |
| Total hunts | {{ rollup.total_hunts }} |
| Total findings | {{ rollup.total_findings }} |
| High-confidence findings | {{ rollup.high_confidence_findings }} |

## Client Breakdown

| Client | Hunts | Findings | High-Conf | Hit Rate |
|--------|-------|----------|-----------|----------|
{% for kpi in rollup.client_kpis -%}
| {{ kpi.client_name }} | {{ kpi.total_hunts }} | {{ kpi.total_findings }} | {{ kpi.high_confidence_findings }} | {{ "%.1f"|format(kpi.hit_rate * 100) }}% |
{% endfor %}

{% if rollup.top_findings -%}
## Top Findings

| Title | Confidence | Count |
|-------|-----------|-------|
{% for f in rollup.top_findings -%}
| {{ f.title }} | {{ f.confidence }} | {{ f.cnt }} |
{% endfor %}
{% endif %}

{% if rollup.recurring_gaps -%}
## Recurring Themes

{% for gap in rollup.recurring_gaps -%}
- {{ gap }}
{% endfor %}
{% endif %}

---
*Generated by MSSP Hunt Agent Analytics*
"""


def generate_weekly_rollup(
    db: HuntDatabase,
    period: str | None = None,
) -> tuple[WeeklyRollup, str]:
    """Generate a weekly rollup report.

    Parameters
    ----------
    db:
        HuntDatabase instance.
    period:
        ISO week string like "2024-W48". Defaults to current week.

    Returns
    -------
    Tuple of (WeeklyRollup model, rendered markdown string).
    """
    if not period:
        now = datetime.now(timezone.utc)
        period = now.strftime("%Y-W%W")

    engine = KPIEngine(db)
    kpis = engine.all_client_kpis(period)
    top = engine.top_findings(limit=5)

    total_hunts = sum(k.total_hunts for k in kpis)
    total_findings = sum(k.total_findings for k in kpis)
    high_conf = sum(k.high_confidence_findings for k in kpis)

    # Approximate start/end dates
    start_date, end_date = _week_to_dates(period)

    rollup = WeeklyRollup(
        period=period,
        start_date=start_date,
        end_date=end_date,
        total_clients_active=len(kpis),
        total_hunts=total_hunts,
        total_findings=total_findings,
        high_confidence_findings=high_conf,
        client_kpis=kpis,
        top_findings=top,
    )

    md = _render_template(_WEEKLY_TEMPLATE, rollup=rollup)
    return rollup, md


def generate_monthly_rollup(
    db: HuntDatabase,
    period: str | None = None,
) -> tuple[MonthlyRollup, str]:
    """Generate a monthly rollup report.

    Parameters
    ----------
    db:
        HuntDatabase instance.
    period:
        Month string like "2024-12". Defaults to current month.

    Returns
    -------
    Tuple of (MonthlyRollup model, rendered markdown string).
    """
    if not period:
        now = datetime.now(timezone.utc)
        period = now.strftime("%Y-%m")

    engine = KPIEngine(db)
    kpis = engine.all_client_kpis(period)
    top = engine.top_findings(limit=10)
    gaps = engine.recurring_gaps(limit=5)

    total_hunts = sum(k.total_hunts for k in kpis)
    total_findings = sum(k.total_findings for k in kpis)
    high_conf = sum(k.high_confidence_findings for k in kpis)

    rollup = MonthlyRollup(
        period=period,
        total_clients_active=len(kpis),
        total_hunts=total_hunts,
        total_findings=total_findings,
        high_confidence_findings=high_conf,
        client_kpis=kpis,
        top_findings=top,
        recurring_gaps=gaps,
    )

    md = _render_template(_MONTHLY_TEMPLATE, rollup=rollup)
    return rollup, md


# ── Helpers ──────────────────────────────────────────────────────────


def _render_template(template_str: str, **kwargs: Any) -> str:
    """Render an inline Jinja2 template."""
    env = Environment(loader=BaseLoader(), autoescape=False)
    tmpl = env.from_string(template_str)
    return tmpl.render(**kwargs)


def _week_to_dates(period: str) -> tuple[str, str]:
    """Convert '2024-W48' to approximate start/end date strings."""
    try:
        parts = period.split("-W")
        year = int(parts[0])
        week = int(parts[1])
        # Monday of that week
        jan1 = datetime(year, 1, 1)
        delta = timedelta(weeks=week)
        start = jan1 + delta - timedelta(days=jan1.weekday())
        end = start + timedelta(days=6)
        return start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")
    except (ValueError, IndexError):
        return period, period
